prjDB_GamingForm_Show/Models/Entities/Depute.cs
using System;
using System.Collections.Generic;

namespace prjDB_GamingForm_Show.Models.Entities;

public partial class Depute
{
    public int DeputeId { get; set; }

    public int ProviderId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime Modifiedate { get; set; }

    public string? DeputeContent { get; set; }

    public decimal Salary { get; set; }

    public int StatusId { get; set; }

    public int RegionId { get; set; }

    public string? Title { get; set; }

    public int ViewCount { get; set; }

    public virtual ICollection<DeputeAction> DeputeActions { get; set; } = new List<DeputeAction>();

    public virtual ICollection<DeputeRecord> DeputeRecords { get; set; } = new List<DeputeRecord>();

    public virtual ICollection<DeputeSkill> DeputeSkills { get; set; } = new List<DeputeSkill>();

    public virtual Member Provider { get; set; } = null!;

    public virtual Region Region { get; set; } = null!;

    public virtual Status Status { get; set; } = null!;
}

prjDB_GamingForm_Show/Models/Entities/DeputeAction.cs
using System;
using System.Collections.Generic;

namespace prjDB_GamingForm_Show.Models.Entities;

public partial class DeputeAction
{
    public int Id { get; set; }

    public int DeputeId { get; set; }

    public int MemberId { get; set; }

    public int ActionId { get; set; }

    public virtual ArticleAction Action { get; set; } = null!;

    public virtual Depute Depute { get; set; } = null!;

    public virtual Member Member { get; set; } = null!;
}

prjDB_GamingForm_Show/Controllers/DeputeController.cs
using DB_GamingForm_Show.Job.DeputeClass;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using prjDB_GamingForm_Show.Models.Entities;
using prjDB_GamingForm_Show.Models.Shop;
using prjDB_GamingForm_Show.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using static prjDB_GamingForm_Show.Controllers.DeputeController;

namespace prjDB_GamingForm_Show.Controllers
{
    public class DeputeController : Controller
    {
        private readonly IWebHostEnvironment _host;
        private readonly DbGamingFormTestContext _db;
        public List<CDeputeViewModel> List { get; set; }
        public List<CDeputeViewModel> Temp { get; set; }
        public DeputeController(IWebHostEnvironment host, DbGamingFormTestContext context)
        {
            _host = host;
            _db = context;
            ListLoad();
        }
        #region 老朱

        //TODO #1 讀資料
        public void ListLoad()
        {
            //test
            Temp = new List<CDeputeViewModel>();
            List = new List<CDeputeViewModel>();
            _db.Members.Load();
            _db.Statuses.Load();
            _db.Regions.Load();
            var data = from n in _db.Deputes.AsEnumerable()
                       orderby n.StartDate descending
                       select new
                       {
                           n.DeputeId,
                           n.Title,
                           Name = n.Provider.Name,
                           SrartDate = n.StartDate.ToString("d"),
                           Modifiedate = n.Modifiedate.ToString("d"),
                           n.DeputeContent,
                           n.Salary,
                           Status = n.Status.Name,
                           n.Region.City,
                           n.Provider.FImagePath
                       };
            CDeputeViewModel x = null;

            foreach (var item in data)
            {
                x = new CDeputeViewModel()
                {
                    id = item.DeputeId,
                    title = item.Title,
                    providername = item.Name,
                    startdate = item.SrartDate,
                    modifieddate = item.Modifiedate,
                    deputeContent = item.DeputeContent,
                    salary = item.Salary,
                    status = item.Status,
                    region = item.City,
                    imgfilepath = item.FImagePath
                };

                List.Add(x);
                Temp = List;
            }
        }

        public IActionResult DeputeList(int? id)
        {
            IEnumerable<CDeputeViewModel> datas = null;
            if (id ==null)
            {
                //ListLoad();
                datas = from n in List
                        select n;
                
            }
            else
            {
                _db.SkillClasses.Load();
                IEnumerable<string> skillname = from n in _db.SkillClasses
                                where n.SkillClassId == id
                                select n.Name;
                foreach (string item in skillname)
                {
                    datas = from n in List
                            where n.deputeContent.Contains(item)
                            select n;
                }
                
               
            }

            return View(datas);

        }

        //TODO #2 搜尋
        public IActionResult Search(CKeyWord vm)
        {
            IEnumerable<CDeputeViewModel> datas = null;
            if (string.IsNullOrEmpty(vm.txtKeyword))
            {
                ListLoad();
                datas = from n in List
                        select n;
            }
            else
            {

                if (string.IsNullOrEmpty(vm.txtKeyword))
                    vm.txtKeyword = "";
                datas = List.Where(n => (n.deputeContent.Trim().ToLower().Contains(vm.txtKeyword.Trim().ToLower()) ||
                                          n.providername.Trim().ToLower().Contains(vm.txtKeyword.Trim().ToLower()) ||
                                          n.title.Trim().ToLower().Contains(vm.txtKeyword.Trim().ToLower()) ||
                                          n.region.Trim().ToLower().Contains(vm.txtKeyword.Trim().ToLower()))
                                          )
                .OrderByDescending(n => n.modifieddate);

            }
            if (datas == null || datas.Count() == 0)
            {
                return Content("No result");
            }
            return Json(datas);
        }

        public IActionResult SearchById(int? id)
        {
            IEnumerable<CDeputeViewModel> datas = null;
            IEnumerable<string> keyword = from n in _db.SerachRecords
                          where n.Id == id
                          select n.Name;

            foreach (string item in keyword)
            {
                if(string.IsNullOrEmpty(item)) 
                    continue;
                datas = List.Where(n => (n.deputeContent.Trim().ToLower().Contains(item.Trim().ToLower()) ||
                                          n.providername.Trim().ToLower().Contains(item.Trim().ToLower()) ||
                                          n.title.Trim().ToLower().Contains(item.Trim().ToLower()) ||
                                          n.region.Trim().ToLower().Contains(item.Trim().ToLower()))
                                          ).OrderByDescending(n => n.modifieddate);

            }
            if (datas == null || datas.Count() == 0)
            {
                return Content("No result");
            }

            return Json(datas);

            
        }
        public IActionResult DetailsSearch(CKeyWord vm)
        {
            IEnumerable<CDeputeViewModel> datas = null;
            if (vm.txtSkillClass == "請選擇..." &&
                vm.txtSkill == "請選擇..." &&
                vm.txtSalary == "請選擇..." &&
                vm.txtRegion == "請選擇...")
            {
                ListLoad();
                datas = from n in List
                        select n;

            }
            else
            {

                if (vm.txtSkillClass == "請選擇...")
                    vm.txtSkillClass = "";
                if (vm.txtSkill == "請選擇...")

                    if (vm.txtRegion == "請選擇...")
                        vm.txtRegion = "";
                if (vm.txtSalary == "請選擇...")
                    vm.txtSalary = "0";
                datas = Temp.Where(n => ((n.deputeContent.Trim().ToLower().Contains(vm.txtKeyword.Trim().ToLower()) ||
                                          n.providername.Trim().ToLower().Contains(vm.txtKeyword.Trim().ToLower()) ||
                                          n.region.Trim().ToLower().Contains(vm.txtKeyword.Trim().ToLower()))) &&
                                          (n.region.Trim().ToLower().Contains(vm.txtRegion.Trim().ToLower())) &&
                                          (n.salary >= (Convert.ToInt32(vm.txtSalary)) &&
                                          n.deputeContent.Trim().ToLower().Contains(vm.txtSkillClass.Trim().ToLower()) &&
                                          n.deputeContent.Trim().ToLower().Contains(vm.txtSkill.Trim().ToLower())
                                          )
                                          )
                   .OrderByDescending(n => n.modifieddate);
                Temp = datas.ToList();
            }
            if (datas == null || datas.Count() == 0)
            {
                return Content("No result");
            }
            return Json(datas);
        }

        //TODO #3 委託詳細
        public IActionResult DeputeDetails(int? id)
        {
            CDeputeViewModel pln = null;
            Depute pDb = _db.Deputes.FirstOrDefault(n => n.DeputeId == id);

            if (pDb != null)
            {
                pln = new CDeputeViewModel();
                pln.providername = pDb.Provider.Name;
                pln.title = pDb.Title;
                pln.startdate = pDb.StartDate.ToString("yyyy/mm/dd HH:mm:ss");
                pln.modifieddate = pDb.Modifiedate.ToString("yyyy/mm/dd HH:mm:ss");
                pln.deputeContent = pDb.DeputeContent;
                pln.salary = pDb.Salary;
                pln.status = pDb.Status.Name;
                pln.region = pDb.Region.City;
                pln.memeberContent = pDb.Provider.Mycomment;
                pln.imgfilepath = pDb.Provider.FImagePath;

            }

            return View(pln);


        }

        //TODO #4 熱門關鍵字
        public IActionResult HotKey(int id)
        {
            var value = (from n in _db.SerachRecords.AsEnumerable()
                         group n by n.Name into q
                         orderby q.Count() descending
                         select new { MyKey = q.Key,MyGroup = q }).Take(id);

            if (value == null)
                return RedirectToAction("DeputeList");

            return Json(value);


        }

        public IActionResult Index()
        {
            //測試網頁樣板用
            return View();
        }
        //下拉
        public IActionResult SkillClassess()
        {
            var datas = from n in _db.SkillClasses
                        select n;
            return Json(datas);
        }
        public IActionResult Region()
        {
            var datas = from n in _db.Regions
                        select n;
            return Json(datas);
        }
        public IActionResult Skills(int? id)
        {
            var datas = _db.Skills.Where(a => a.SkillClassId == id);
            return Json(datas);
        }
        public IActionResult DeputeCount()
        {
            var SkillClasses = _db.SkillClasses;
            List<CDeputeViewModel> slist = new List<CDeputeViewModel>();

prjDB_GamingForm_Show/Views/Depute/Apply.cshtml
@model prjDB_GamingForm_Show.Models.Entities.Depute

@{
    ViewData["Title"] = "Apply";
    Layout = "~/Views/Shared/_Layout_DBM.cshtml";
}

<h2>應徵</h2>

<h4>請輸入您的應徵資訊</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Apply">
            <input type="text" name="Id" hidden>
            <div class="form-group">
                <label class="control-label">委託主題</label>
                <input class="form-control" type="text" value="@Model.Title" disabled />
            </div>
            <div class="form-group">
                <label class="control-label">委託內容</label>
                <textarea class="form-control" type="text" rows="6" disabled>@Model.DeputeContent</textarea>
            </div>
            <div class="form-group">
                <label class="control-label">提供報酬</label>
                <input class="form-control" type="text" value="@Model.Salary.ToString("$###,###,##0.00")" disabled />
            </div>
            <div class="form-group" hidden>
                <label asp-for="DeputeId" class="control-label"></label>
                <input name="DeputeId" value="@Model.DeputeId" class="form-control" />
            </div>
            <div class="form-group" hidden>
                <label  class="control-label">會員編號</label>
                <input name="MemberId" value="@ViewBag.memberid"class="form-control"/>
            </div>
            <div class="form-group" hidden>
                <label class="control-label">ApplyStatusId</label>
                <input name="ApplyStatusId" value="5" class="form-control"/>
            </div>
            <div>
                <label  class="control-label">應徵補充資訊</label>
                <textarea class="form-control" name="RecordContent" rows="4" cols="50" placeholder="在這裡輸入您的應徵補充資訊..."></textarea>
            </div>
            <div class="form-group mt-3">
                <a asp-action="DeputeMain" class="btn btn-secondary">返回</a>
                <input type="submit" value="送出並應徵" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

prjDB_GamingForm_Show/Views/Depute/DeputeDetails.cshtml
@model DB_GamingForm_Show.Job.DeputeClass.CDeputeViewModel

@{
    ViewData["Title"] = "DeputeDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
    // this.Model
}

<head>
    <!-- Depute -->
    <meta charset="utf-8">
    <title>JobEntry - Job Portal Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <!-- Favicon -->
    <link href="~/layout/jobentry-1.0.0/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/layout/jobentry-1.0.0/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/layout/jobentry-1.0.0/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->

    <link href="~/layout/jobentry-1.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/layout/jobentry-1.0.0/css/style.css" rel="stylesheet">
    <!-- Depute -->

</head>
<!-- Header End -->
<div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">懸賞細節</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb text-uppercase">
                @Html.ActionLink("懸賞首頁","DeputeMain","Depute",null,new{@class ="breadcrumb-item"})
                @Html.ActionLink("選賞清單","DeputeList","Depute",null,new{@class ="breadcrumb-item"})
                <li class="breadcrumb-item text-white active" aria-current="page">詳細資料</li>
            </ol>
        </nav>
    </div>
</div>
<!-- Header End -->
<!-- Job Detail Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">

        
            
                <div class="row gy-5 gx-4">
                    <div class="col-lg-8">
                        <div class="d-flex align-items-center mb-5">
                            <img class="flex-shrink-0 img-fluid border rounded" src="~/images/04.jfif" alt="" style="width: 80px; height: 80px;">
                            <div class="text-start ps-4">
                        <h3 class="mb-3">@Html.DisplayFor(model => model.title)</h3>
                        <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>@Html.DisplayFor(model => model.region)</span>
                        <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>@Html.DisplayFor(model => model.modifieddate)</span>
                        <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>@Html.DisplayFor(model => model.salary)</span>
                            </div>
                        </div>

                        <div class="mb-5">
                            <h4 class="mb-3">懸賞內容</h4>
                    <p>@Html.DisplayFor(model => model.deputeContent)</p>
                            <h4 class="mb-3">懸賞職責</h4>
                        <p></p>
                            <ul class="list-unstyled">
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Dolor justo tempor duo ipsum accusam</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Elitr stet dolor vero clita labore gubergren</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Rebum vero dolores dolores elitr</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Est voluptua et sanctus at sanctus erat</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Diam diam stet erat no est est</li>
                            </ul>
                            <h4 class="mb-3">懸賞需求</h4>
                            <p>Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor</p>
                            <ul class="list-unstyled">
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Dolor justo tempor duo ipsum accusam</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Elitr stet dolor vero clita labore gubergren</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Rebum vero dolores dolores elitr</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Est voluptua et sanctus at sanctus erat</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Diam diam stet erat no est est</li>
                            </ul>
                        </div>

                        <div class="">
                            <h4 class="mb-4">Apply For The Job</h4>
                            <form>
                                <div class="row g-3">
                                    <div class="col-12 col-sm-6">
                                        <input type="text" class="form-control" placeholder="Your Name">
                                    </div>
                                    <div class="col-12 col-sm-6">
                                        <input type="email" class="form-control" placeholder="Your Email">
                                    </div>
                                    <div class="col-12 col-sm-6">
                                        <input type="text" class="form-control" placeholder="Portfolio Website">
                                    </div>
                                    <div class="col-12 col-sm-6">
                                        <input type="file" class="form-control bg-white">
                                    </div>
                                    <div class="col-12">
                                        <textarea class="form-control" rows="5" placeholder="Coverletter"></textarea>
                                    </div>
                                    <div class="col-12">
                                        <button class="btn btn-primary w-100" type="submit">Apply Now</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="bg-light rounded p-5 mb-4 wow slideInUp" data-wow-delay="0.1s">
                            <h4 class="mb-4">懸賞摘要</h4>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>開始時間: @Html.DisplayFor(model => model.startdate)</p>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>最後更新: @Html.DisplayFor(model => model.modifieddate)</p>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>懸賞金額: @Html.DisplayFor(model => model.salary)</p>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>懸賞地點: @Html.DisplayFor(model => model.region)</p>
                    <p class="m-0"><i class="fa fa-angle-right text-primary me-2"></i>懸賞狀態: @Html.DisplayFor(model => model.status)</p>
                        </div>
                        <div class="bg-light rounded p-5 wow slideInUp" data-wow-delay="0.1s">
                            <h4 class="mb-4">自我介紹</h4>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>懸賞金主: @Html.DisplayFor(model => model.providername)</p>
                    <p class="m-0">@Html.DisplayFor(model => model.memeberContent)</p>
                        </div>
                    </div>
                </div>
            
        
    </div>

</div>
<!-- Job Detail End -->
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/layout/jobentry-1.0.0/lib/wow/wow.min.js"></script>
<script src="~/layout/jobentry-1.0.0/lib/easing/easing.min.js"></script>
<script src="~/layout/jobentry-1.0.0/lib/waypoints/waypoints.min.js"></script>
<script src="~/layout/jobentry-1.0.0/lib/owlcarousel/owl.carousel.min.js"></script>
<script>
    const button = document.querySelector('#car');

    button.addEventListener('mouseover', () => {
        button.style.backgroundColor = '#a81d1d';
    });

    button.addEventListener('mouseout', () => {
        button.style.backgroundColor = '';
    });
</script>



<h2>DeputeDetails</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.providername)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.startdate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.modifieddate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.deputeContent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.skillname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.count)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        <tr>
            <td>
                @Html.DisplayFor(modelItem => modelItem.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.providername)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.startdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.modifieddate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.deputeContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.region)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.skillname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.count)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>

    </tbody>
    </table>

prjDB_GamingForm_Show/Views/Depute/Edit.cshtml
@model prjDB_GamingForm_Show.Models.Entities.Depute

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout_DBM.cshtml";
}

<h2>委託資訊修改</h2>
<h4>請輸入修改資訊</h4>
<hr>

<div class="row">
    <div class="col-md-10">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="DeputeId" class="control-label"></label>
                <input asp-for="DeputeId" class="form-control" />
                <span asp-validation-for="DeputeId" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="ProviderId" class="control-label"></label>
                <input asp-for="ProviderId" class="form-control" />
                <span asp-validation-for="ProviderId" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Modifiedate" class="control-label"></label>
                <input asp-for="Modifiedate" class="form-control" />
                <span asp-validation-for="Modifiedate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">標題</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="form-label">委託內容</label>
                <textarea asp-for="DeputeContent" class="form-control" style="height:200px"></textarea>
                <span asp-validation-for="DeputeContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">提供報酬</label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">狀態</label>
                <select name="status" class="form-select" id="selStatus" aria-label="Default select example">
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">地區</label>
                <select name="region" class="form-select" id="selRegion" aria-label="Default select example">
                </select>
            </div>
            <div class="form-group">
                <a asp-action="personal" class="btn btn-secondary">取消</a>
                <input type="submit" value="送出並修改" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        async function loadRegions() {
            const response = await fetch(`@Url.Content("~/depute/regions")`);
            const datas = await response.json();
            const regions = datas.map(region => `<option value="${region.city}">${region.city}</option>`);
            document.querySelector("#selRegion").innerHTML = regions.join("");
            document.querySelector("#selRegion").selectedIndex = @Model.RegionId-1;
        }
        loadRegions();

        const deputeid = @Model.DeputeId;
        async function loadStatuses(deputeID) {
            const response = await fetch(`@Url.Content("~/depute/editDeputeStatuses")?id=${deputeID}`);
            const datas = await response.json();
            console.log(datas);
            const statuses = datas.map(status => `<option value="${status.status}">${status.status}</option>`);
            document.querySelector("#selStatus").innerHTML = statuses.join("");
        }
        loadStatuses(deputeid);
    </script>
}

prjDB_GamingForm_Show/Views/Depute/PartialReceiveList.cshtml
@model IEnumerable<prjDB_GamingForm_Show.Models.Entities.DeputeRecord>

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<table class="table table-dark table-striped table-bordered">

    <tr>
        <th hidden></th>
        <th class="col-1">
            #
        </th>
        <th class="col-4">
            內容
        </th>
        <th class="col-1">
            狀態
        </th>
        <th class="col-1">
            報酬
        </th>
        <th class="col-2">
            更新時間
        </th>
        <th class="col-3"></th>
    </tr>


    @{
        int count = 0;
        foreach (var i in Model)
        {
            count++;
            <tr>
            <td hidden>@i.Id</td>
                <td hidden>@i.DeputeId</td>
                <td class="col-1">
                    @count
                </td>
                <td class="col-3">
                    @i.Depute.DeputeContent
                </td>
                <td class="col-1">
                    @i.ApplyStatus.Name
                </td>
                <td class="col-1">
                    @i.Depute.Salary.ToString("$###,###,##0.##")
                </td>
                <td class="col-1">
                    @i.Depute.Modifiedate.ToString("yyyy/MM/dd HH:mm")
                </td>
                <td class="col-3">
                    @Html.ActionLink("詳細資料", "Details", new { id = i.Id }, new { @class = "btn btn-secondary" }) |
                    @Html.ActionLink("撤回", "DeleteDeputeRecord", "Depute", new { id = i.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    }
</table>